[package]
name = "youtube-music"
description = "A library for fetching Youtube Music metadata"
readme = "readme.md"
repository = "https://github.com/jakubslaby09/rust-ytmapi"
license = "MIT OR Apache-2.0"
version = "1.2.0"
edition = "2021"
exclude = ["res*.json", "pointers.md"]

[dependencies]
reqwest = { version = "0.11.12", features = ["json"] }
tokio = { version = "1.23.1", features = ["full"] }
lazy-regex = "2.3.0"
serde_json = "1.0.85"

[lib]
name = "youtube_music"
