[package]
name = "rust-ytmapi"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.12", features = ["json"] }
tokio = { version = "1.21.1", features = ["full"] }
lazy-regex = "2.3.0"
#json = "0.12.4"
serde_json = "1.0.85"