[package]
name = "rust-ytmapi"
version = "1.0.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.12", features = ["json"] }
tokio = { version = "1.21.1", features = ["full"] }
lazy-regex = "2.3.0"
serde_json = "1.0.85"